/**
 * React adapter for `.tsx` / `.jsx` islands (Phase 16a).
 *
 * The framework-agnostic Phase 16 contract is `mount(el, props)` —
 * the user writes their own glue. For React, that glue is mechanical:
 * `createRoot(el).render(React.createElement(Component, props))`.
 *
 * Phase 16a auto-injects the glue at island-serve time. The user
 * writes:
 *
 *   export default function Counter(props) { … }
 *
 * The `/_aflare/island?path=...` route detects the default export,
 * runs the source through `wrapReactIslandSource()`, and the
 * resulting bundle exports both `default` (the original component)
 * and `mount` (the React adapter glue). The browser dynamic-imports
 * the bundle and the hydration runtime calls `mount(island, props)`.
 *
 * Two surfaces:
 *   - `wrapReactIslandSource(source)` — pure function. Compile-time.
 *   - `MOUNT_REACT_ISLAND_SOURCE` — string source for the
 *     `/_aflare/react.js` route the wrapper imports from. Default
 *     resolves React + react-dom via esm.sh; user overrides for
 *     self-hosting.
 */

const REACT_ADAPTER_PATH = "/_aflare/react.js";

/**
 * Detect a top-level default-export site. Two flavours covered:
 *
 *  1. The "raw" Astro/React authoring form, before any transform:
 *       export default function Foo(...) {…}
 *       export default class Foo {…}
 *       export default Foo;
 *       export default <expr>;
 *
 *  2. The esbuild-normalised form that the `/_aflare/island` route
 *     produces *after* the TS+JSX transform pass:
 *       function Foo(...) {…}
 *       export { Foo as default };
 *
 * For (1) the index points at `export`. For (2) the index points at
 * `export { ... as default ... }` and the captured `name` is the
 * source name being aliased — we use it to bind `__aflareDefault`.
 *
 * Naïve line-anchored matching: occurrences inside multi-line
 * strings or comments at column-0 are not distinguished. Matches the
 * pragmatic-detection approach the inline bundler uses elsewhere.
 */
export type DefaultExportDetection =
	| { found: false }
	| { found: true; kind: "expr"; index: number }
	| { found: true; kind: "alias"; index: number; matchEnd: number; name: string };

export function findDefaultExport(source: string): DefaultExportDetection {
	const reExpr = /^[ \t]*export[ \t]+default[ \t]+/m;
	const mExpr = reExpr.exec(source);
	// Match the esbuild-normalised form: `export { X as default };`
	// (multiple specifiers in the same export list aren't generated by
	// esbuild for a single default export, but accept them anyway).
	const reAlias = /^[ \t]*export[ \t]*\{\s*([A-Za-z_$][\w$]*)\s+as[ \t]+default\s*\}\s*;?/m;
	const mAlias = reAlias.exec(source);

	if (mExpr && (!mAlias || mExpr.index < mAlias.index)) {
		return { found: true, kind: "expr", index: mExpr.index };
	}
	if (mAlias) {
		return {
			found: true,
			kind: "alias",
			index: mAlias.index,
			matchEnd: mAlias.index + mAlias[0].length,
			name: mAlias[1] as string,
		};
	}
	return { found: false };
}

/**
 * Wrap a TSX/JSX island source with the React adapter glue.
 *
 * Input (after esbuild's TS+JSX transform):
 *
 *   import { jsx as _jsx } from "react/jsx-runtime";
 *   export default function Counter(props) { return _jsx("button", {...}); }
 *
 * Output:
 *
 *   import { jsx as _jsx } from "react/jsx-runtime";
 *   import { mountReactIsland as __aflareMount } from "/_aflare/react.js";
 *   const __aflareDefault = function Counter(props) { return _jsx("button", {...}); };
 *   export default __aflareDefault;
 *   export function mount(__el, __props) {
 *     return __aflareMount(__aflareDefault, __el, __props);
 *   }
 *
 * If no default export is present, the source is returned unchanged
 * — user-authored `mount` exports stay load-bearing. Existing
 * vanilla-JS islands keep working.
 */
export function wrapReactIslandSource(source: string): string {
	const detect = findDefaultExport(source);
	if (!detect.found) return source;

	const adapterImport = `import { mountReactIsland as __aflareMount } from "${REACT_ADAPTER_PATH}";\n`;
	const tail =
		"\nexport function mount(__el, __props) {\n" +
		"  return __aflareMount(__aflareDefault, __el, __props);\n" +
		"}\n";

	if (detect.kind === "expr") {
		// `export default <expr>` → `const __aflareDefault = <expr>;
		// export default __aflareDefault;`. Works for function, class,
		// and bare-expression forms.
		const re = /^([ \t]*)export[ \t]+default[ \t]+/m;
		const replaced = source.replace(re, "$1const __aflareDefault = ");
		return `${adapterImport}${replaced}\nexport default __aflareDefault;${tail}`;
	}

	// `export { Foo as default };` (esbuild-normalised form). Keep the
	// source identifier visible at module scope (it already is —
	// esbuild lifted the function declaration out), strip the alias
	// re-export, and bind `__aflareDefault` to the named ref.
	const before = source.slice(0, detect.index);
	const after = source.slice(detect.matchEnd);
	const stripped = `${before}${after}`;
	const bind = `\nconst __aflareDefault = ${detect.name};\nexport default __aflareDefault;\n`;
	return `${adapterImport}${stripped}${bind}${tail}`;
}

/**
 * Static source for the `/_aflare/react.js` route — the adapter
 * users get out of the box. Pulls React + react-dom/client from
 * esm.sh; users can override the route to self-host or pin a
 * different version. The exported `mountReactIsland(Component, el,
 * props)` function uses `createRoot(el).render(...)` and stores
 * the root on the element so subsequent re-mounts can `unmount()`
 * cleanly (rare, but supports view-transition re-renders).
 */
export const MOUNT_REACT_ISLAND_SOURCE = `// astroflare React adapter
import * as React from "https://esm.sh/react@18.3.1";
import * as ReactDOMClient from "https://esm.sh/react-dom@18.3.1/client";

const ROOT_KEY = "__aflareReactRoot";

export function mountReactIsland(Component, el, props) {
	if (!el) return;
	let root = el[ROOT_KEY];
	if (!root) {
		root = ReactDOMClient.createRoot(el);
		el[ROOT_KEY] = root;
	}
	root.render(React.createElement(Component, props ?? {}));
}

export function unmountReactIsland(el) {
	const root = el && el[ROOT_KEY];
	if (root) {
		root.unmount();
		delete el[ROOT_KEY];
	}
}

// Re-exports for users who want to pull React from this same chunk
// rather than esm.sh directly.
export { React };
export { ReactDOMClient };
`;
